import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/lib/redux/provider"



const urbanist = Urbanist({  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Test App",
  description: "Generated by create mcimildoro",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.className}  min-h-screen`}>
          <ReduxProvider> 
            {children}  
          </ReduxProvider>
      </body>
    </html>
  );
}
